added cd

diff --git a/.github/workflows/build-artifacts.yaml b/.github/workflows/build-artifacts.yaml
--- a/.github/workflows/build-artifacts.yaml
+++ b/.github/workflows/build-artifacts.yaml
@@ -47,8 +47,9 @@ jobs:
           ./bin/golang/ssm-params-downloads-by-env -org Ualett -env SandBox -scheduled no -app backend
 
       - name: Install dependencies
-        working-directory: ./bo-backend
-        run: npm install > /dev/null || { echo "An error occurred."; exit 1; }
+        run: |
+          ls -ltra && pwd && \
+          npm install > /dev/null || { echo "An error occurred."; exit 1; }
 
       - name: Set up Meteor
         uses: meteorengineer/setup-meteor@v2
@@ -56,7 +57,6 @@ jobs:
           meteor-release: '2.15'
 
       - name: Listing Files
-        working-directory: ./bo-backend
         run: |
           ls -ltra && pwd && node -v && npm -v 
 
