added cd

diff --git a/.github/workflows/build-artifacts.yaml b/.github/workflows/build-artifacts.yaml
--- a/.github/workflows/build-artifacts.yaml
+++ b/.github/workflows/build-artifacts.yaml
@@ -33,10 +33,15 @@ jobs:
       - name: Install dependencies
         run: npm install > /dev/null || { echo "An error occurred."; exit 1; }
 
-      # - name: Set up Meteor
-      #   uses: meteorengineer/setup-meteor@v2
-      #   with:
-      #     meteor-release: '2.15'
+      - name: Set up Meteor
+        uses: meteorengineer/setup-meteor@v2
+        with:
+          meteor-release: '2.15'
+
+      - name: Build application
+        run: |
+          meteor build --server-only --architecture os.linux.x86_64 && \
+          cd build/programs/server && npm install --omit-dev > /dev/null || { echo "An error occurred."; exit 1; } 
 
       # - name: Build application
       #   run: |
