added pollito

diff --git a/.github/workflows/s3.yaml b/.github/workflows/s3.yaml
--- a/.github/workflows/s3.yaml
+++ b/.github/workflows/s3.yaml
@@ -1,6 +1,5 @@
 name: Dev deploy App
 
-
 on:
   workflow_dispatch:
     inputs:
@@ -31,18 +30,40 @@ jobs:
     runs-on: ubuntu-22.04
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
       - name: Validate PR number
+        continue-on-error: false
         run: |
-          if ! [[ "${{ github.event.inputs.pr_number }}" =~ ^[0-9]+$ ]]; then
+          PR_NUMBER="${{ github.event.inputs.pr_number }}"
+
+          # Verificar si el PR_NUMBER es numérico
+          if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
             echo "Error: El número del Pull Request debe ser un número entero."
             exit 1
           fi
-          echo "Pull Request número ${{ github.event.inputs.pr_number }} es válido."
+
+          # Verificar si el PR existe utilizando la API de GitHub
+          PR_API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
+          PR_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$PR_API_URL")
+
+          # Verificar si el PR no existe
+          if echo "$PR_RESPONSE" | grep -q '"message": "Not Found"'; then
+            echo "Error: El Pull Request #$PR_NUMBER no existe en el repositorio ${{ github.repository }}."
+            exit 1
+          fi
+
+          # Verificar si la autenticación es inválida
+          if echo "$PR_RESPONSE" | grep -q '"message": "Bad credentials"'; then
+            echo "Error: Credenciales inválidas para acceder a la API de GitHub."
+            exit 1
+          fi
+
+          echo "Pull Request #$PR_NUMBER es válido."
+
+      - name: Checkout PR branch
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: refs/pull/${{ github.event.inputs.pr_number }}/merge
 
       - name: Get short SHA
         id: git-sha
