fix

diff --git a/.github/workflows/s3.yaml b/.github/workflows/s3.yaml
--- a/.github/workflows/s3.yaml
+++ b/.github/workflows/s3.yaml
@@ -28,7 +28,6 @@ defaults:
 jobs:
   build-and-deploy:
     runs-on: ubuntu-22.04
-    if:  ${{ inputs.pr_number }} 
 
     steps:
       - name: Checkout repository
@@ -37,22 +36,31 @@ jobs:
       - name: Install jq
         run: sudo apt-get install -y jq
 
-      - name: Validate PR existence
+      - name: Validate PR number and existence
         id: validate-pr
-        continue-on-error: false
         run: |
           PR_NUMBER="${{ github.event.inputs.pr_number }}"
-          
+
+          # Verificar si el PR_NUMBER es numérico
+          if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
+            echo "Error: El valor del Pull Request debe ser un número entero."
+            exit 1
+          fi
+
+          # Configurar la URL de la API de GitHub para el PR
           GITHUB_API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
           AUTH_HEADER="Authorization: Bearer ${{ secrets.GH_PAT }}"
 
+          # Llamada a la API de GitHub para obtener el PR
           PR_RESPONSE=$(curl -s -H "$AUTH_HEADER" "$GITHUB_API_URL")
 
+          # Verificar si el PR existe
           if echo "$PR_RESPONSE" | grep -q '"message": "Not Found"'; then
             echo "Error: El Pull Request #$PR_NUMBER no existe en el repositorio ${{ github.repository }}."
             exit 1
           fi
 
+          # Verificar si la autenticación es inválida
           if echo "$PR_RESPONSE" | grep -q '"message": "Bad credentials"'; then
             echo "Error: Credenciales inválidas para acceder a la API de GitHub."
             exit 1
