dado

diff --git a/.github/workflows/s3.yaml b/.github/workflows/s3.yaml
--- a/.github/workflows/s3.yaml
+++ b/.github/workflows/s3.yaml
@@ -33,20 +33,35 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Install jq
+        run: sudo apt-get install -y jq
+
       - name: Validate PR existence
         id: validate-pr
         run: |
           PR_NUMBER="${{ github.event.inputs.pr_number }}"
           
-          PR_API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
-          PR_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GH_PAT }}" $PR_API_URL)
+          # Configurar el token de GitHub
+          GITHUB_API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
+          AUTH_HEADER="Authorization: Bearer ${{ secrets.GH_PAT }}"
 
-          if [[ "$PR_STATUS" -ne 200 ]]; then
-            echo "Error: El Pull Request #$PR_NUMBER no existe o no es accesible."
+          # Llamada a la API de GitHub para obtener el PR
+          PR_RESPONSE=$(curl -s -H "$AUTH_HEADER" "$GITHUB_API_URL")
+
+          # Verificar si hay un mensaje de error en la respuesta
+          if echo "$PR_RESPONSE" | grep -q '"message": "Not Found"'; then
+            echo "Error: El Pull Request #$PR_NUMBER no existe en el repositorio ${{ github.repository }}."
+            exit 1
+          fi
+
+          # Verificar si la autenticación es inválida
+          if echo "$PR_RESPONSE" | grep -q '"message": "Bad credentials"'; then
+            echo "Error: Credenciales inválidas para acceder a la API de GitHub."
             exit 1
           fi
 
           echo "Pull Request #$PR_NUMBER es válido."
+
 
       - name: Get short SHA
         id: git-sha
