deleted bitbucket file

diff --git a/.github/workflows/s3.yaml b/.github/workflows/s3.yaml
--- a/.github/workflows/s3.yaml
+++ b/.github/workflows/s3.yaml
@@ -16,6 +16,7 @@ env:
   SSH_HOST_PUBLIC_DNS: ${{ vars.SSH_HOST_PUBLIC_DNS }}
   SSH_HOST_PUBLIC_IP: ${{ vars.SSH_HOST_PUBLIC_IP }}
   APP_NAME: ${{ github.event.repository.name }}
+  GH_PAT: ${{ secrets.GH_PAT }}
   S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
   NODEJS_VERSION: "14.21.3"
   METEOR_VERSION: "2.8.1"
@@ -31,6 +32,21 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      - name: Validate PR existence
+        id: validate-pr
+        run: |
+          PR_NUMBER="${{ github.event.inputs.pr_number }}"
+          
+          PR_API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
+          PR_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GH_PAT }}" $PR_API_URL)
+
+          if [[ "$PR_STATUS" -ne 200 ]]; then
+            echo "Error: El Pull Request #$PR_NUMBER no existe o no es accesible."
+            exit 1
+          fi
+
+          echo "Pull Request #$PR_NUMBER es válido."
 
       - name: Get short SHA
         id: git-sha
